ekf_filter_node:
  ros__parameters:
    frequency: 20.0             #20.0
    sensor_timeout: 0.1        #0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map             
    odom_frame: odom           
    base_link_frame: base_link
    world_frame: odom
    
    # initial_state: [0.0, 0.0, 0.0, 
    #                 0.0, 0.0, 0.0, 
    #                 0.0, 0.0, 0.0, 
    #                 0.0, 0.0, 0.0, 
    #                 0.0, 0.0, 0.0]  
    #x     , y     , z,
    #roll  , pitch , yaw, 
    #vx    , vy    , vz,
    #vroll , vpitch, vyaw,
    #ax    , ay    , az
    odom0: diff_cont/odom
    odom0_config: [true, true, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10            #10
    odom0_nodelay: true
    odom0_differential: true
    odom0_relative: false

    imu0: bno055/imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_nodelay: false         #false
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10         #10
    imu0_remove_gravitational_acceleration: false
